FROM golang:1.10.1-alpine3.7
ADD k8s_portal /
RUN apk update && apk add git bash vim openssl ca-certificates && go get github.com/dimm0/k8s_portal || true && \
  cd /go/src/github.com/dimm0/k8s_portal && git checkout ps && \
  rm -rf /media && ln -s /go/src/github.com/dimm0/k8s_portal/media /media && ln -s /go/src/github.com/dimm0/k8s_portal/templates /templates && \
  go get -u github.com/golang/dep/cmd/dep && dep ensure && ./codegen.sh
RUN mkdir /sessions
CMD ["sleep", "360000000"]
EXPOSE 80
